### ISSUE TITLE
Same Modbus Hub for the second and third storage

### ISSUE THREAD

**Issue by Jan051286** [Superduper1969/MarstekVenus-ElfinEW11#3]
Hi, in the "marstek_venus_battery2_control.yaml" for example is the same modbus hub used as in the first one.
The Name for the second has to be for example "hub: MarstekVenus2"

Wrong:
hub: MarstekVenus

Rigth:
hub: MarstekVenus2

Additional:
The Utilitymeter has to be "daily_discharge2"

Wrong:
  utility_meter:
    daily_discharge:
      name: My Battery2 Daily Discharging in kWh

Right:
  utility_meter2:
    daily_discharge:
      name: My Battery2 Daily Discharging in kWh

**Comment by Kawakasi** [comment]
@Jan051286
What you wrote helped me a lot. However, I now get the following error message:
Setup of package 'marstek_venus_battery2_control' failed: Integration 'utility_meter2' not found.

**Comment by Jan051286** [comment]
@Kawakasi 
I think your problem is that you added a "2" behind the "unility_meter:"

> In Home Assistant, the YAML entry utility_meter: is a predefined integration block that is recognized and processed by the Home Assistant platform. If you instead write utility_meter2:, Home Assistant no longer recognizes this block as a valid integration – and therefore throws an error.>

That is the correct code

>  utility_meter:
     daily_discharge:
      name: My Battery2 Daily Discharging in kWh
      unique_id: my_battery2_daily_discharging_in_kwh
      source: sensor.my_battery2_discharging_in_kwh
      cycle: daily
     daily_charge:
      name: My Battery2 Daily Charging in kWh
      unique_id: my_battery2_daily_charging_in_kwh
      source: sensor.my_battery2_charging_in_kwh
      cycle: daily>

**Comment by netsloh** [comment]
Unfortunately, that doesn't work either. This is how it works:
  
```
utility_meter:
    daily_discharge_battery_two:
      name: Battery TWO Daily Discharging in kWh
      unique_id: battery_two_daily_discharging_in_kwh
      source: sensor.battery_two_discharging_in_kwh
      cycle: daily


    daily_charge_battery_two:
      name: Battery TWO Daily Charging in kWh
      unique_id: battery_two_daily_charging_in_kwh
      source: sensor.battery_two_charging_in_kwh
      cycle: daily
```
